from __future__ import annotations

import json
import re
from collections import Counter

from tools.core.config import OUTPUT_DIR, RAW_DIR, REPORTS_DIR, save_json_atomic, save_text_atomic
from tools.core.json_io import load_json_file
from tools.core.logger import logger


TASKPACK_DIR = OUTPUT_DIR / "taskpacks"
TASKPACK_LIMIT = 80
TASK_ACTION_LIMITS = {
    "Import Now": 20,
    "Import With Review": 40,
    "Do Not Import Yet": 20,
}


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", str(value or "")).strip("-").lower()
    return slug or "task"


def _task_intent(action: str) -> str:
    if action == "Import Now":
        return "safe_import"
    if action == "Import With Review":
        return "reviewed_import"
    return "blocker_resolution"


def _verification_steps(decision: dict) -> list[str]:
    steps = ["Run the Nexora SAGE static gate after any import or manual adjustment."]
    if "run_browser_smoke" in decision.get("required_actions", []):
        route = (decision.get("route") or {}).get("smoke_path") or "/"
        steps.append(f"Run generated UI smoke spec for route `{route}`.")
    if "verify_external_packages" in decision.get("required_actions", []):
        steps.append("Verify external package availability and version compatibility before copying code.")
    if "resolve_internal_dependency_paths" in decision.get("required_actions", []):
        steps.append("Resolve internal dependency paths before attempting import.")
    if "repair_source_closure" in decision.get("required_actions", []):
        steps.append("Repair or regenerate dependency closure; source package is incomplete.")
    return steps


def _proof_contract(decision: dict) -> dict:
    evidence = decision.get("evidence", {}) or {}
    commands = [
        "python -m compileall -q tools codemaps.py sage.py",
        "python tools/validate_source_contracts.py",
        "python -m tools.engines.merge_simulation_engine",
        "python -m tools.engines.merge_decision_cockpit",
    ]
    if "run_browser_smoke" in decision.get("required_actions", []):
        commands.append("npx playwright test <generated-smoke-spec>")
    return {
        "required_proof_commands": commands,
        "expected_artifacts": [
            "output/.raw/merge_simulation.json",
            "output/.raw/merge_decision_cockpit.json",
            "output/.raw/ai_task_packs.json",
            evidence.get("smoke_spec_path") or "output/scripts/ui_smoke_specs/<candidate>.spec.ts",
        ],
        "rollback_criteria": [
            "Any required proof command fails.",
            "Merge decision regresses to Do Not Import Yet after changes.",
            "Target conflicts or missing source files increase.",
            "Browser smoke reports uncaught console/runtime errors.",
        ],
        "human_review_checklist": [
            "Confirm target path and host ownership before copying files.",
            "Review dependency harness provider/router/i18n/browser mocks.",
            "Review confidence components and unresolved/external dependency lists.",
            "Approve rollback plan before applying product source changes.",
        ],
        "confidence_components": evidence.get("confidence_components", {}),
    }


def render_task_pack(decision: dict) -> str:
    evidence = decision.get("evidence", {}) or {}
    route = decision.get("route", {}) or {}
    proof_contract = _proof_contract(decision)
    title = f"{decision.get('action')}: {decision.get('candidate')} from {decision.get('source')}"
    lines = [
        f"# {title}",
        "",
        "Generated by the Nexora SAGE AI Task Pack Generator.",
        "",
        "## Decision",
        f"- action: `{decision.get('action')}`",
        f"- candidate: `{decision.get('candidate')}`",
        f"- source: `{decision.get('source')}`",
        f"- target: `{decision.get('target_path')}`",
        f"- intent: `{_task_intent(str(decision.get('action') or ''))}`",
        f"- closure files: `{decision.get('closure_size', 0)}`",
        "",
        "## Evidence",
        f"- source contract: `{evidence.get('source_contract_file') or '-'}`",
        f"- smoke spec: `{evidence.get('smoke_spec_path') or '-'}`",
        f"- route: `{route.get('smoke_path') or '-'}`",
        f"- route framework: `{route.get('framework') or '-'}`",
        f"- reasons: `{', '.join(decision.get('reasons', [])) or '-'}`",
        "",
        "## Guardrails",
        "- Do not overwrite existing host files without explicit review.",
        "- Do not copy generated taskpack files into product source.",
        "- Preserve host architecture boundaries and public APIs.",
        "- Prefer composition/adapters over direct replacement for reviewed imports.",
        "",
        "## Required Actions",
    ]
    for action in decision.get("required_actions", []):
        lines.append(f"- `{action}`")
    copy_files = evidence.get("copy_files_sample", []) or []
    omitted = int(evidence.get("copy_files_omitted", 0) or 0)
    if copy_files:
        lines.extend(["", "## Source Files To Inspect"])
        for path in copy_files[:20]:
            lines.append(f"- `{path}`")
        if omitted:
            lines.append(f"- ... `{omitted}` additional closure files omitted; inspect the source contract before broad copy.")
    lines.extend(["", "## Verification"])
    for step in _verification_steps(decision):
        lines.append(f"- {step}")
    lines.extend(["", "## Proof Contract", "", "### Required Commands"])
    for command in proof_contract["required_proof_commands"]:
        lines.append(f"- `{command}`")
    lines.extend(["", "### Expected Artifacts"])
    for artifact in proof_contract["expected_artifacts"]:
        lines.append(f"- `{artifact}`")
    lines.extend(["", "### Rollback Criteria"])
    for criterion in proof_contract["rollback_criteria"]:
        lines.append(f"- {criterion}")
    lines.extend(["", "### Human Review"])
    for item in proof_contract["human_review_checklist"]:
        lines.append(f"- [ ] {item}")
    unresolved = evidence.get("unresolved_internal_deps", []) or []
    external = evidence.get("external_deps", []) or []
    conflicts = evidence.get("target_conflicts", []) or []
    if unresolved or external or conflicts:
        lines.extend(["", "## Blockers To Clear"])
        for dep in unresolved[:20]:
            lines.append(f"- unresolved internal dependency: `{dep}`")
        for dep in external[:20]:
            lines.append(f"- external dependency: `{dep}`")
        for path in conflicts[:20]:
            lines.append(f"- target conflict: `{path}`")
    return "\n".join(lines) + "\n"


def build_task_pack_record(decision: dict) -> tuple[dict, str]:
    action = str(decision.get("action") or "Review")
    filename = f"{_slug(action)}-{_slug(str(decision.get('source') or 'source'))}-{_slug(str(decision.get('candidate') or 'candidate'))}.md"
    path = TASKPACK_DIR / filename
    record = {
        "candidate": decision.get("candidate"),
        "source": decision.get("source"),
        "action": action,
        "intent": _task_intent(action),
        "target_path": decision.get("target_path"),
        "taskpack_path": f"output/taskpacks/{filename}",
        "required_actions": decision.get("required_actions", []),
        "reasons": decision.get("reasons", []),
        "source_contract_file": (decision.get("evidence", {}) or {}).get("source_contract_file"),
        "copy_files_sample": (decision.get("evidence", {}) or {}).get("copy_files_sample", []),
        "copy_files_omitted": (decision.get("evidence", {}) or {}).get("copy_files_omitted", 0),
        "proof_contract": _proof_contract(decision),
    }
    return record, str(path)


def _selected_decisions(decisions: list[dict]) -> list[dict]:
    selected = []
    counts = Counter()
    for item in decisions:
        action = str(item.get("action") or "")
        if counts[action] >= TASK_ACTION_LIMITS.get(action, 0):
            continue
        selected.append(item)
        counts[action] += 1
        if len(selected) >= TASKPACK_LIMIT:
            break
    return selected


def run_ai_task_pack_generator() -> dict:
    logger.info("Generating AI task packs from merge decision cockpit...")
    cockpit = load_json_file(RAW_DIR / "merge_decision_cockpit.json", {})
    decisions = [item for item in (cockpit.get("decisions", []) if isinstance(cockpit, dict) else []) if isinstance(item, dict)]
    selected = _selected_decisions(decisions)
    TASKPACK_DIR.mkdir(parents=True, exist_ok=True)

    records = []
    for decision in selected:
        record, path = build_task_pack_record(decision)
        save_text_atomic(path, render_task_pack(decision))
        records.append(record)

    action_counter = Counter(record["action"] for record in records)
    payload = {
        "meta": {"kind": "ai_task_packs", "version": "v1"},
        "summary": {
            "generated": len(records),
            "actions": dict(action_counter),
            "taskpack_dir": "output/taskpacks",
            "source_artifact": "output/.raw/merge_decision_cockpit.json",
        },
        "taskpacks": records,
    }
    save_json_atomic(RAW_DIR / "ai_task_packs.json", payload)

    lines = [
        "# AI Task Pack Generator",
        "",
        "AI/human execution packets generated from the merge decision cockpit.",
        "",
        f"- generated: `{len(records)}`",
        f"- actions: `{dict(action_counter)}`",
        "",
        "## Task Packs",
    ]
    for record in records[:100]:
        lines.append(
            f"- `{record['action']}` | `{record['candidate']}` <- {record['source']} | `{record['taskpack_path']}`"
        )
    save_text_atomic(REPORTS_DIR / "ai_task_packs.md", "\n".join(lines))
    logger.info("AI task pack artifacts written.")
    return payload


if __name__ == "__main__":
    run_ai_task_pack_generator()
