from __future__ import annotations

import json
import re
from pathlib import Path

from tools.core.analysis_snapshot_lineage import write_current_atlas_lineage
from tools.core.atlas_io import load_atlas_data
from tools.core.config import RAW_DIR, REPORTS_DIR, SCRIPTS_DIR, save_json_atomic, save_text_atomic
from tools.core.json_io import load_json_file
from tools.core.logger import logger
from tools.core.merge_review_hardening_policy import policy_int, policy_string, policy_string_list, ui_smoke_spec_policy
from tools.core.unmanaged_atomic_io import native_filesystem_path


SPEC_DIR = SCRIPTS_DIR / "ui_smoke_specs"


def _clear_managed_specs() -> int:
    native_spec_dir = Path(native_filesystem_path(SPEC_DIR))
    if not native_spec_dir.exists():
        return 0
    removed = 0
    for stale_path in native_spec_dir.glob("*.spec.ts"):
        stale_path.unlink(missing_ok=True)
        removed += 1
    return removed


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", str(value or "").strip()).strip("-").lower()
    return slug or "ui-candidate"


def _quote(value: str) -> str:
    return json.dumps(str(value or ""))


def _console_filters(assertions: list[str]) -> str:
    lines = [
        "const consoleErrors: string[] = [];",
        "page.on('console', message => {",
        "  if (message.type() === 'error') consoleErrors.push(message.text());",
        "});",
        "page.on('pageerror', error => consoleErrors.push(error.message));",
    ]
    if "no_missing_provider_or_context_error" in assertions:
        lines.append("const providerErrorPattern = /provider|context|store|zustand|cannot read/i;")
    return "\n".join(lines)


def _smoke_policy_lines() -> list[str]:
    policy = ui_smoke_spec_policy()
    retries = max(0, policy_int(policy, "retries"))
    return [
        "  // [SAGE Hardening] Retry policy is owned by merge_review_hardening_policy.json.",
        f"  test.describe.configure({{ retries: {retries} }});",
    ]


def _smoke_runtime_guard_lines(route: str) -> list[str]:
    policy = ui_smoke_spec_policy()
    allowed_hostnames = policy_string_list(policy, "allowed_hostnames")
    auth_redirect_pattern = policy_string(policy, "auth_redirect_pattern")
    hidden_failure_pattern = policy_string(policy, "hidden_failure_text_pattern")
    lines: list[str] = []
    if policy.get("block_outbound_network", True):
        host_list = ", ".join(_quote(host) for host in allowed_hostnames)
        lines.extend([
            "",
            "    // [SAGE Hardening] Network allowlist is owned by merge_review_hardening_policy.json.",
            f"    const allowedHostnames = new Set([{host_list}]);",
            "    await page.route('**/*', route => {",
            "      const url = new URL(route.request().url());",
            "      if (allowedHostnames.has(url.hostname)) {",
            "        return route.continue();",
            "      }",
            "      return route.abort();",
            "    });",
        ])
    lines.extend([
        "",
        f"    await page.goto({_quote(route)});",
        "    await page.waitForLoadState('networkidle');",
        "",
        "    // [SAGE Hardening] Auth redirect and hidden-failure checks are policy-owned.",
        f"    await expect(page).not.toHaveURL(new RegExp({_quote(auth_redirect_pattern)}, 'i'));",
        "",
        "    await expect(page.locator('body')).toBeVisible();",
        f"    await expect(page.locator('body')).not.toContainText(new RegExp({_quote(hidden_failure_pattern)}, 'i'));",
    ])
    return lines


def render_playwright_smoke_spec(candidate: dict) -> str:
    name = str(candidate.get("name") or "UI candidate")
    source = str(candidate.get("source") or "UNKNOWN")
    target_path = str(candidate.get("target_path") or "")
    source_contract = str(candidate.get("source_contract_file") or "")
    smoke = candidate.get("smoke_plan") or {}
    closure = candidate.get("dependency_closure_plan") or {}
    route = str(smoke.get("suggested_route") or "/")
    assertions = [str(item) for item in smoke.get("assertions", []) if item]
    required_contracts = [str(item) for item in closure.get("required_contracts", []) if item]

    lines = [
        "import { expect, test } from '@playwright/test';",
        "",
        f"test.describe({_quote(f'Nexora SAGE UI smoke: {name}')}, () => {{",
        *_smoke_policy_lines(),
        "",
        f"  test({_quote(f'{name} renders without hidden runtime-contract failures')}, async ({{ page }}) => {{",
        "    // Generated by Nexora SAGE. Keep this as a pre-merge smoke template, not as final product UX coverage.",
    ]
    for line in _console_filters(assertions).splitlines():
        lines.append(f"    {line}")
    lines.extend(_smoke_runtime_guard_lines(route))
    if "no_missing_provider_or_context_error" in assertions:
        lines.append("    expect(consoleErrors.filter(error => providerErrorPattern.test(error))).toEqual([]);")
    if "no_console_error_on_initial_render" in assertions:
        lines.append("    expect(consoleErrors).toEqual([]);")
    if "no_visible_raw_i18n_keys" in assertions:
        lines.append("    await expect(page.locator('body')).not.toContainText(/[a-z0-9]+\\.[a-z0-9_.-]+/i);")
    if "critical_layout_elements_have_nonzero_size" in assertions:
        lines.extend([
            "    const bodyBox = await page.locator('body').boundingBox();",
            "    expect(bodyBox?.width ?? 0).toBeGreaterThan(0);",
            "    expect(bodyBox?.height ?? 0).toBeGreaterThan(0);",
        ])
    if "store_selectors_resolve_expected_shape" in assertions:
        lines.append("    await expect(page.locator('body')).not.toContainText(/undefined is not|cannot read properties/i);")

    lines.extend([
        "  });",
        "});",
        "",
        "/*",
        "Nexora SAGE metadata",
        f"- candidate: {name}",
        f"- source: {source}",
        f"- target_path: {target_path}",
        f"- source_contract_file: {source_contract or '-'}",
        f"- required_contracts: {', '.join(required_contracts) or '-'}",
        f"- recommended_gate: {candidate.get('recommended_gate')}",
        "*/",
        "",
    ])
    return "\n".join(lines)


def _candidate_to_spec_record(candidate: dict) -> dict:
    name = str(candidate.get("name") or "ui_candidate")
    source = str(candidate.get("source") or "unknown")
    studio = str(candidate.get("studio") or "workspace")
    filename = f"{_slug(studio)}-{_slug(source)}-{_slug(name)}.spec.ts"
    spec_path = SPEC_DIR / filename
    return {
        "candidate": name,
        "source": source,
        "studio": studio,
        "required": bool((candidate.get("smoke_plan") or {}).get("required")),
        "recommended_gate": candidate.get("recommended_gate"),
        "risk_tier": candidate.get("risk_tier"),
        "target_path": candidate.get("target_path"),
        "source_contract_file": candidate.get("source_contract_file"),
        "suggested_route": (candidate.get("smoke_plan") or {}).get("suggested_route"),
        "required_contracts": (candidate.get("dependency_closure_plan") or {}).get("required_contracts", []),
        "spec_path": f"output/scripts/ui_smoke_specs/{filename}",
    }, spec_path


def run_ui_smoke_spec_generator() -> dict:
    logger.info("Generating UI smoke spec templates from runtime contracts...")
    atlas = load_atlas_data()
    ui_runtime = load_json_file(RAW_DIR / "ui_runtime_contracts.json", {})
    candidates = ui_runtime.get("merge_candidates", []) if isinstance(ui_runtime, dict) else []
    smoke_candidates = [
        item for item in candidates
        if isinstance(item, dict) and item.get("recommended_gate") == "browser_smoke_required"
    ]

    Path(native_filesystem_path(SPEC_DIR)).mkdir(parents=True, exist_ok=True)
    removed_stale_specs = _clear_managed_specs()
    if removed_stale_specs:
        logger.info(f"Removed {removed_stale_specs} stale generated UI smoke specs.")
    records: list[dict] = []
    for candidate in smoke_candidates:
        record, spec_path = _candidate_to_spec_record(candidate)
        save_text_atomic(spec_path, render_playwright_smoke_spec(candidate))
        records.append(record)

    payload = {
        "meta": {"kind": "ui_smoke_specs", "version": "v1"},
        "summary": {
            "generated": len(records),
            "removed_stale_specs": removed_stale_specs,
            "source_artifact": "output/.raw/ui_runtime_contracts.json",
            "spec_dir": "output/scripts/ui_smoke_specs",
        },
        "specs": records,
    }
    save_json_atomic(RAW_DIR / "ui_smoke_specs.json", payload)
    write_current_atlas_lineage(
        artifact_id="ui_smoke_specs",
        producer="tools.engines.ui_smoke_spec_generator",
        artifact_payload=payload,
        atlas=atlas,
        dependency_payloads={"ui_runtime_contracts": ui_runtime},
    )

    lines = [
        "# UI Smoke Spec Generator",
        "",
        "Generated Playwright-style pre-merge smoke templates for UI candidates that Nexora SAGE marked as `browser_smoke_required`.",
        "",
        f"- generated specs: `{len(records)}`",
        f"- output dir: `{payload['summary']['spec_dir']}`",
        "",
        "## Generated Specs",
    ]
    for record in records[:80]:
        lines.append(
            f"- `{record['candidate']}` <- {record['source']} | `{record['risk_tier']}` | "
            f"route `{record.get('suggested_route') or '/'}` | `{record['spec_path']}`"
        )
    save_text_atomic(REPORTS_DIR / "ui_smoke_specs.md", "\n".join(lines))
    logger.info("UI smoke spec templates written.")
    return payload


if __name__ == "__main__":
    run_ui_smoke_spec_generator()
