from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, Iterable, List

import tools.core.config as config
from tools.core.config import DYNAMIC_CONFIG, DOCTRINE, CONFIG_FILE, OVERRIDES_FILE

OVERRIDES_PATH = OVERRIDES_FILE


def _load_overrides() -> dict:
    if not OVERRIDES_PATH.exists():
        return {}
    return config._load_json(OVERRIDES_PATH, repair=True)


def _tokenize_alias_candidates(*values: str) -> set[str]:
    candidates = set()
    for value in values:
        if not value:
            continue
        normalized = re.sub(r"[^A-Z0-9_]+", "_", str(value).upper()).strip("_")
        if normalized:
            candidates.add(normalized)
            for part in normalized.split("_"):
                if len(part) >= 4:
                    candidates.add(part)
    return candidates


def _build_project_name_aliases() -> Dict[str, str]:
    aliases: Dict[str, str] = {"MAIN": "MAIN"}
    overrides = _load_overrides()
    variations = DYNAMIC_CONFIG.get("variations", {}) or {}
    variation_aliases = overrides.get("variation_aliases", {}) or {}
    canonical_names = {str(name) for name in variations.keys()}

    for canonical_name, raw_path in variations.items():
        canonical_name_str = str(canonical_name)
        candidates = _tokenize_alias_candidates(canonical_name, raw_path)
        aliases[canonical_name_str] = canonical_name_str
        for candidate in candidates:
            # Never allow token aliases from other names/paths to hijack an actual
            # canonical project key (e.g. EXAMPLE_APPS producing APPS token).
            if candidate in canonical_names and candidate != canonical_name_str:
                continue
            aliases.setdefault(candidate, canonical_name_str)

    for canonical_name, payload in variation_aliases.items():
        if not isinstance(payload, dict):
            continue
        canonical_name_str = str(canonical_name)
        discovery_key = payload.get("discovery_key", "")
        raw_path = payload.get("path", "")
        for candidate in _tokenize_alias_candidates(canonical_name, discovery_key, raw_path):
            if candidate in canonical_names and candidate != canonical_name_str:
                continue
            aliases.setdefault(candidate, canonical_name_str)

    return aliases


PROJECT_NAME_ALIASES = _build_project_name_aliases()
PROJECT_DISPLAY_NAMES = {
    str(key): str(value)
    for key, value in (DYNAMIC_CONFIG.get("project_display_names", {}) or {}).items()
    if isinstance(key, str) and isinstance(value, str)
}


def canonical_project_name(name: str) -> str:
    n = re.sub(r"[^A-Z0-9_]+", "_", (name or "").upper()).strip("_")
    return PROJECT_NAME_ALIASES.get(n, n)


def project_display_name(name: str) -> str:
    canonical = canonical_project_name(name)
    return PROJECT_DISPLAY_NAMES.get(canonical, canonical)


def _listify(value) -> List[str]:
    if isinstance(value, list):
        return [str(v) for v in value]
    return [str(value)]


def _load_projects_from_schema() -> Dict[str, List[str]]:
    # DYNAMIC_CONFIG is already a merge of discovery and config.
    # We must de-duplicate by physical path to avoid double-processing.
    variations = DYNAMIC_CONFIG.get("variations", {}) or {}
    if not variations:
        return {"MAIN": ["src"]}

    # Path -> Key map to detect duplicates
    path_to_key: Dict[str, str] = {}
    result: Dict[str, List[str]] = {}
    
    # Priority: We want to keep keys that are NOT auto-generated by discovery if possible.
    # Discovery keys are usually long UPPER_SNAKE derived from folder names.
    # But for simplicity, we just ensure one key per path.
    
    for raw_name, raw_paths in variations.items():
        canon = canonical_project_name(str(raw_name))
        paths = _listify(raw_paths)
        if not paths: continue
        
        main_path = paths[0].rstrip("/.")
        if main_path in path_to_key:
            existing_key = path_to_key[main_path]
            # If current key is shorter or "more manual looking", we could swap, 
            # but for now just prioritize the first one encountered (which usually is from config due to merge order).
            continue
            
        path_to_key[main_path] = canon
        result[canon] = paths
        
    return result


PROJECTS = _load_projects_from_schema()


# Target architecture map (matches current src/lifecycle-modules structure).
STUDIO_TO_MODULE = DOCTRINE.get("studio_to_module_map", {})
MODULE_TO_STUDIO = {module: studio for studio, module in STUDIO_TO_MODULE.items()}

# Project-specific studio path hints (regex -> studio).
PROJECT_STUDIO_REGISTRY = DOCTRINE.get("project_path_hints", {})


def resolve_projects(root_path: Path, filter_keys: Iterable[str] | None = None) -> Dict[str, Path]:
    """
    Returns canonical project-name -> existing path map.
    If filter_keys is provided, keys are normalized before filtering.
    """
    allowed = None
    if filter_keys:
        allowed = {canonical_project_name(str(k)) for k in filter_keys}

    resolved_paths: Dict[str, Path] = {}
    for proj_name, paths in PROJECTS.items():
        canon = canonical_project_name(proj_name)
        if allowed and canon not in allowed:
            continue
        for p in paths:
            candidate = root_path / p
            if candidate.exists() and candidate.is_dir():
                resolved_paths[canon] = candidate
                break
    return resolved_paths


def resolve_runtime_projects(root_path: Path) -> Dict[str, Path]:
    """Resolve projects using the active runtime project filter, if any."""
    return resolve_projects(root_path, config.PROJECT_FILTER)


def release_scope_project_keys(available_projects: Iterable[str]) -> set[str]:
    """Resolve projects whose findings may govern the current release subject."""
    available = {canonical_project_name(str(project)) for project in available_projects}
    project_roles = DYNAMIC_CONFIG.get("project_roles", {}) or {}
    role_scope = {
        canonical_project_name(str(project))
        for project, role in project_roles.items()
        if str(role).lower() in {"host", "release", "primary"}
    }
    if role_scope:
        return role_scope & available if available else role_scope
    if "MAIN" in available:
        return {"MAIN"}
    return available


def studio_for_module_name(module_name: str) -> str | None:
    normalized = str(module_name or "").lower()
    if not normalized:
        return None
    for module, studio in MODULE_TO_STUDIO.items():
        if normalized == module.lower() or normalized.endswith(module.lower()) or module.lower() in normalized:
            return studio
    return None
